### PR TITLE
fix(FocusManager): Replaces implementation with focus-trap-react

### LINKED ISSUE #27: Can't re-assign focus to another Focus Trap
**Describe the bug**
When using the `FocusManager` component inside, for instance, a Drawer, a Dialog or any other type of UI that needs focus trapping features, the trap works fine.
However, when the user presses enter on, for instance, a button or something that opens another element that also requires focus to be drawn onto it (like a Popover, or another other UI that requires focus trapping as well), then the first `FocusManager` just won't let go of the focus.

**Expected behaviour**
Focus should be redirected as needed, when the user needs.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  MacBook Pro M2
 - OS: MacOS Sonoma 14.5
 - Browser Microsoft Edge 126.0.2592.102
 - Version any version from this package

### PR DESCRIPTION
**Pull request by JoaoTMDias**
## Because
In order to fix the bug reported on issue 2

## This Commit
Does a re-implementation of the `FocusManager`, by replacing the current functionality, with the functionality provided by the ["focus-trap-react" package](https://www.npmjs.com/package/focus-trap-react).

In order to keep the same API as before, it makes them still available as before, but changes the default values for `autoFocus`, `restoreFocus` and `contain` props. It also exposes the "focus-trap" configuration API on the `options` prop.

As such, the component itself also gains a whole set of new functionalities, made possible by the `focus-trap` package.

BREAKING CHANGE: autoFocus, restoreFocus and contain are now set to true by default
BREAKING CHANGE: the `useFocusManager` was reimplemented. Since we no longer use a React context state management solution to travel between elements, the hook was re-implemented as an optional way to facilitate the creation of a `FocusTrap` instance, but without using the provided element by the package.

Closes #27

### CODE REVIEW

File: src/components/focus-manager/helpers/index.ts [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+import { Options } from "focus-trap";
+
+/**
+ * Sets the initial focus element.
+ */
+export function getInitialFocus(
+	autoFocus: FocusManagerProps["autoFocus"],
+	initialFocus: Options["initialFocus"],
+) {
+	if (autoFocus === true) {
```
Comment (tiagocastro070) [inline src/components/focus-manager/helpers/index.ts:17]: Isn't this enough?
```js
if (autoFocus) {
```

File: src/components/focus-manager/useFocusManager.tsx [hunk 2]
```diff
@@ -4,52 +4,91 @@
...
-	return useContext(FocusContext);
+export function useFocusManager<GenericElement extends HTMLElement | SVGElement>(
+	props: Omit<FocusManagerProps, "children">,
+	ref: RefObject<GenericElement> | MutableRefObject<GenericElement>,
+): UseFocusManagerWithRef;
+export function useFocusManager(
+	props: Omit<FocusManagerProps, "children">,
+	ref?: never,
+): UseFocusManagerAsProps;
+export function useFocusManager<GenericElement extends HTMLElement | SVGElement>(
```
Comment (tiagocastro070) [inline src/components/focus-manager/useFocusManager.tsx:43]: Was this a mistake? Exporting 3 functions with the name `useFocusManager` on the same file.

Comment (JoaoTMDias) [reply src/components/focus-manager/useFocusManager.tsx:43]: Nope, it is a typescript feature [called function overloading](https://blog.logrocket.com/implementing-function-overloading-typescript/).
Basically, you can define multiple function signatures so that, depending on the input, the expected output is different. 
For example, if you pass only the props, the hook behaves as if inside a component, otherwise it will behave like a hook that provides the `FocusTrap` functionality.

File: src/components/focus-manager/helpers/index.ts (hunk 1 above)
Comment (JoaoTMDias) [reply src/components/focus-manager/helpers/index.ts:18]: I've changed the implementation of this to be more clear:
```ts
/**
 * Sets the initial focus element.
 */
export function getInitialFocus(
	autoFocus: FocusManagerProps["autoFocus"],
	initialFocus: Options["initialFocus"],
) {
	// If true, resumes the normal behaviour
	if (autoFocus === true) {
		return undefined;
	}

	// If false, prevents the autoFocus from happening
	else if (autoFocus === false) {
		return false;
	}

	// If is nil, uses the value defined in the `initialFocus` param,
	// which if also nil, resumes the normal behaviour
	return initialFocus;
}
```

**Review by tiagocastro070 — APPROVED** [review]

**Comment by CarolinaRMarques** [comment]
I can’t approve here, but from my side, everything seems good to go! 

One suggestion for improvement would be to include a small video or screenshot of the demo. While this may not be necessary for this particular case, I believe it can always help people understand the context a bit better. This is just a personal preference, but I think it would be beneficial for future PRs.

Nonetheless, great job!!

**Review by CarolinaRMarques — APPROVED** [review]
